[package]
name = "httcp"
version = "0.1.0"
authors = ["Nurahmadie <nurahmadie@gmail.com>"]

[dependencies]
clap = "2.19.2"
rocket = "0.1.2"
rocket_codegen = "0.1.2"

[dependencies.lazy_static]
git = "https://github.com/rust-lang-nursery/lazy-static.rs"